version: '3'

services:
  app:
    build: .
    volumes:
      - ".:/home/fiap/app"
  
  mysql-dev:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Fiap1234
      